name = "kriterion-entry"
version = "0.1.0"
defaultTargets = ["Construction", "Proof", "Submission"]

[[require]]
name = "bn254-scalar-multiplication"
git = "https://github.com/Kriterion-cc/kriterion-challenge"
rev = "e66a3eaa37c95b66380002a1a3333e140aee28c7"
subDir = "bn254-scalar-multiplication"

[[lean_lib]]
name = "Construction"

[[lean_lib]]
name = "Proof"

[[lean_lib]]
name = "Submission"
